[package]
name = "aoc_rs"
version = "0.1.0"
authors = [
  "janreggie"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bimap = "0.6"
clap = "2"
num = "0.4.0"
priority-queue = "1.2"
sscanf = "0.1.4"
